user_control/urls.py
from django.conf.urls import *
    
urlpatterns = patterns('',
    url('', include('social.apps.django_app.urls', namespace='social')),
	(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'pages/login.html'}, 'default_login'),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/welcome/?next=/'}, 'default_logout'),

	(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'settings/password/change.html'}),
    (r'^password_change_done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'settings/password/change_done.html'}),
    (r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'settings/password/reset.html',
        'email_template_name': "email/reset_password.html",
        'post_reset_redirect': '/users/password_reset_done/'}, 'password_reset'),
    (r'^password_reset_done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'settings/password/reset_done.html'}, 'password_reset_done'),
    (r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': '/', 'template_name': 'settings/password/reset_confirm.html'}, 'password_reset_confirm'),
)

urlpatterns += patterns('user_control.views',
    (r'^delete/(?P<userIds>[\d,]{0,100})/$', 'delete_users'),
    url(r'^signup/$', 'signup', name='signup'),

    (r'^change_name/$', 'change_name'),
    (r'^change_email/$', 'change_email'),
    (r'^change_email_complete/(?P<hash_string>[0-9A-Za-z]+)/$', 'change_email_complete'),

    url(r'^confirm/(?P<confirmationCode>[\w\s\d]{0,20})/(?P<username>[\w\s\d]{0,50})/$', 'confirm', name="confirm"),
)

watsan/urls.py
from django.conf.urls import *
from django.contrib import admin, admindocs
from django.contrib.auth.views import logout, login, password_reset, password_reset_done, password_reset_complete, password_reset_confirm
from django.views.generic import RedirectView, TemplateView
from watsan.views import *

admin.autodiscover()
    
urlpatterns = [
    url(r'^landing/$', TemplateView.as_view(template_name="landing.html"), name='watsan_landing'),
    url(r'^login/$', login, {'template_name': 'registration/login.html'},  name='watsan_login'),
    url(r'^logout/$', logout, {'template_name': 'registration/login.html'}, name='watsan_logout' ),
    url(r'^$', RedirectView.as_view(url='/dashboard'), name='watsan_home'),

    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^map/(?P<projectId>[0-9]*)$', the_map),
    url(r'^project/(?P<projectId>[0-9]*)$', project),
    url(r'^ncwsc/(?P<projectId>[0-9]*)$', ncwsc),
    url(r'^alts/(?P<projectId>[0-9]*)$', alts),

    url(r'^register/$', RedirectView.as_view(url='/register/org'), name='watsan_register'),
    url(r'^register/org/$', register_org, name='watsan_register_org'),
    url(r'^register/user/$', register_user, name='watsan_register_user'),
    url(r'^register/final/$', register_final, name='watsan_register_final'),

    url(r'^password_reset/$', password_reset,
        {'template_name': 'password_reset/password_reset.html',
        'post_reset_redirect': '/watsan/password_reset_done/'}),
    url(r'^password_reset_done/$', password_reset_done, {'template_name': 'password_reset/password_reset_done.html'}),
    url(r'^password_reset_complete/$', password_reset_complete, {'template_name': 'password_reset/password_reset_complete.html'}),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, 
        {'post_reset_redirect' : '/watsan/password_reset_complete', 'template_name': 'password_reset/password_reset_confirm.html'}),

    url(r'^about/$', about, name='about'),
    url(r'^settings/$', settings, name='settings'),
    #(r'^settings/password_change/$', password_change, {'template_name': 'watsan/dashboard/password_change.html'}),
    #(r'^settings/password_change_done/$', password_change_done, {'template_name': 'watsan/dashboard/password_change_done.html'}),
    url(r'^settings/change_user_name/$', change_user_name),
    url(r'^settings/change_user_email/$', change_user_email),
    url(r'^settings/change_user_email_complete/(?P<hash_string>[0-9A-Za-z]+)/$', change_user_email_complete),
    
    url(r'^saveLandmark/$', save_landmark),
    url(r'^saveSearchString/$', save_search_string), 
    url(r'^map/site/save/$', save_site),
    url(r'^map/site/edit/$', edit_site),
    url(r'^map/site/delete/$', delete_site),
    url(r'^map/check_site/$', check_site_placement),
    url(r'^project/save/$', save_project),
    url(r'^admin/', admin.site.urls)
]

user_control/models.py
from django import forms
from django.contrib.gis.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.forms.widgets import RadioSelect, HiddenInput, PasswordInput

class UserProfile(models.Model):
    user = models.ForeignKey(User)
    next = models.CharField(default="/", max_length=100)

    number = models.CharField(max_length=20, blank=True)
    secondary_number = models.CharField(max_length=20, blank=True)
    gender = models.CharField(blank=True, choices=(('male', 'Male'), ('female', 'Female')), max_length=10)
    picture = models.ImageField(upload_to="UserAvatars", blank=True, null=True)
    has_mpesa = models.NullBooleanField()
    organization = models.CharField(max_length=255, blank=True)

    confirmation_code = models.CharField(max_length=20 ,blank=True, null=True)

    class Meta:
        app_label = 'user_control'
        db_table = 'user_control_userprofile'
    
    def __unicode__(self):
        return self.user.username+"'s profile"

class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    username = forms.CharField(max_length=30, required=True)

    old_password = forms.CharField(max_length=30, required=False, widget=PasswordInput())
    new_password = forms.CharField(max_length=30, required=False, widget=PasswordInput())
    new_password_again = forms.CharField(max_length=30, required=False, widget=PasswordInput())
    
    def clean(self):
        cleaned_data = super(UserEditForm, self).clean()
        old_password = cleaned_data.get("old_password")
        new_password = cleaned_data.get("new_password")
        new_password2 = cleaned_data.get("new_password_again")
        if old_password and new_password:
            if not self.instance.check_password(old_password):
                self._errors["old_password"] = self.error_class([u"Incorrect Password!"])
            elif not new_password2:
                self._errors["new_password_again"] = self.error_class([u"Must enter new password twice"])
            elif not new_password == new_password2:
                self._errors["new_password"] = self.error_class([u"Your new passwords didn't match!"])
        return cleaned_data
    
    class Meta:
        model = UserProfile
        fields = ('first_name','last_name','username', 'old_password','new_password','new_password_again')

class UserProfileForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    number = forms.CharField(max_length=20, required=False)
    secondary_number = forms.CharField(max_length=20, required=False)
    gender = forms.CharField(required=False, widget=forms.RadioSelect(choices=(('male', 'Male'), ('female', 'Female'))), max_length=10)
    picture = forms.ImageField(required=False)
    has_mpesa = forms.NullBooleanField(required=True, widget=RadioSelect(choices=((None, 'Unknown'), (True, 'Yes'), (False, 'No'))))
    organization = forms.CharField(required=False, max_length=255)
    
    class Meta:
        model = UserProfile
        fields = ('email','number','secondary_number','gender','picture','has_mpesa')
        exclude = ('user', 'next')
        
class AddMemberForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=False)
    number = forms.CharField(max_length=20, required=False)
    can_export_data = forms.BooleanField(required=False)
    is_admin = forms.BooleanField(help_text="This will enable this user to add and remove users, and make other major changes to your collective (including exporting data)", required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'number')

class NewUserForm(forms.ModelForm):
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField()
    password1 = forms.CharField(label='Password',max_length=30, widget=PasswordInput())
    organization = forms.CharField(label='Organization', max_length=30, required=False)

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data.get("email")
            if User.objects.filter(email=email).exists():
                self._errors["email"] = self.error_class([u"Email is already registered."])
                return False
            return email
        else:
            return False

    class Meta:
        model = User
        fields = ('username', 'email', 'password1','organization')

user_control/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.contrib.auth.views import password_reset, password_reset_confirm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib.sites.models import Site
from user_control.models import NewUserForm, UserProfile
from user_control import utils

def signup(request):
    if request.method == "POST":
        user_form = NewUserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password1'])
            user.save()

            confirmation_code = utils.generate_confirmation_code()
            userprofile = UserProfile(user=user, confirmation_code=confirmation_code)
            userprofile.save()
            
            html_content = render_to_string('email/confirmation.html', { 'username': user.username, 'confirmation_code': confirmation_code, 'domain': Site.objects.get_current().domain })
            text_content = strip_tags(html_content) 
            message = EmailMultiAlternatives('Email Confirmation', text_content, 'connect@spatialcollective.com', [user.email])
            message.attach_alternative(html_content, "text/html")
            message.send()

            return render(request, 'pages/signup.html')
        return render(request, 'pages/signup.html', {'userform': user_form})
    else:
        user_form = NewUserForm()
        return render(request, 'pages/signup.html', {'userform': user_form})


def confirm(request, confirmationCode, username):
	user = User.objects.get(username=username)
	profile = UserProfile.objects.get(user=user)

	if profile.confirmation_code == confirmationCode:
		profile.confirmation_code = ''
		profile.save()
		user.save()

		html_content = render_to_string('email/welcome.html', { 'username': user.username })
		text_content = strip_tags(html_content) 
		message = EmailMultiAlternatives('Welcome to Spatial Collective!', text_content, 'connect@spatialcollective.com', [user.email])
		message.attach_alternative(html_content, "text/html")
		message.send()
		
		user.backend='django.contrib.auth.backends.ModelBackend'
		login(request, user)
	return redirect('home')



@login_required
def change_name(request):
	if request.method == 'POST':
		new_name = EditUserNameForm(request.POST).save(commit=False)
		request.user.first_name = new_name.first_name
		request.user.last_name = new_name.last_name
		request.user.save();
		return redirect('/settings')
	else:
		new_name_form = EditUserNameForm({'first_name': request.user.first_name, 'last_name': request.user.last_name })
		return render(request, 'settings/change_name.html', { 'new_name_form': new_name_form })

@login_required
def change_email(request):
	if request.method == 'POST':
		new_email_form = ChangeUserEmailForm(request.POST)
		if new_email_form.is_valid():
			new_email = new_email_form.save(commit=False)

			if User.objects.filter(email=new_email.email).exists():
				new_email_form._errors['email'] = new_email_form.error_class([u"That email is already registered."])
				return render(request, 'settings/email/change.html', {'new_email_form': new_email_form })
			else:
				new_email.user = request.user
				new_email.hash_string = uuid.uuid1().hex[:9]
				transfered = False
				new_email.save()

				message = render_to_string('watsan/email/change.html', { 'link': 'http://localhost:8000/watsan/settings/change_user_email_complete/'+new_email.hash_string })
				send_mail('Changing your email', message, 'kariuki@ishuah.com', [new_email.email])

			return render(request, 'settings/email/change_done.html')
		else:
			return render(request, 'settings/email/change.html', {'new_email_form': new_email_form })
	else:
		new_email_form = ChangeUserEmailForm()
		return render(request, 'settings/email/change.html', {'new_email_form': new_email_form })

def change_email_complete(request, hash_string):
	try:
		new_email = NewEmail.objects.get(hash_string=hash_string)
	except:
		return render(request, 'settings/email/change_error.html')
	user = new_email.user 
	user.email = new_email.email
	user.username = new_email.email
	user.save()

	new_email.transfered = True
	new_email.hash_string = ''
	new_email.save()

	if request.user.is_authenticated():
		logout(request)

	return render(request, 'settings/email/change_complete.html')

@permission_required('base_map.manage_map')
def delete_users(request, userIds=None):
	user_id_list = filter (lambda i:  i != ' ', userIds.split(','))
	count = 0
	for u  in user_id_list:
		if u and not User.objects.get(pk=u) == request.user:
			User.objects.get(pk=u).delete()
			count += 1
		elif u:
			messages.error(request, "Sorry, you can't delete yourself yet!")
	if count > 0:
		messages.success(request, "Deleted %i users" % (count))
	return redirect('/settings/members/')

user_control/templates/pages/login.html
{% extends "base_map/base.html" %}

{% block header_content %}
{% endblock %}

{% block content %}
	<div id='small-box' class="text-center">
		<h1 class="page-title">Log in</h1>
			<form method="post" action="{% url 'default_login' %}">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ next }}" />
				{% if form.errors %}
				<ul class="errorlist">
					<li>The username or password entered do not match an existing account.</li>
				</ul>
				{% endif %}
				<div>
					<input required type='text' id="username" onfocus='removeDefault(this.id)' onblur="restoreDefault(this.id)" class='wide' name='username' placeholder='Username' />
					<input required type='password' id="password" onfocus='removeDefault(this.id)' onblur="restoreDefault(this.id)" class='wide' name='password' placeholder='Password' />
					<a id='forgot' href="{% url 'password_reset' %}">Forgot your password?</a>
				</div>
				<div class='placeholder'>
					<div id='goto'><p>Don't have an account? <a href="{% url 'signup' %}">Sign Up</a></p></div>
					<button id="done" class="btn success medium" type="submit" name="submit" >Log in</button>
				</div>
			</form>
			
	</div>
{% endblock %}

user_control/templates/pages/login2.html
{% extends "watsan/landing.html" %}

{% block header %}
	<header>
		<nav id='sysnav'>
			<span>Not registered?
			<a class='button' href="{% url 'watsan.views.register_org' %}">Sign Up</a></span>
			<br>
		</nav>
	</header>
{% endblock %}

{% block content %}
	<div id="login-box">
		{% if form.errors %}
			<div id="login-errors">
				<p>Your email and password did not match</p>
				<p>Please try again</p>
			</div>
		{% endif %}
		<form id="login-form" class="margin" method="post" action="{% url 'watsan_login' %}">
			{% csrf_token %}
			<input type='text' id="username" placeholder='Email' class='input-box' name='username' onfocus='removeDefault(this.id)' onblur="restoreDefault(this.id)" />
			<input type='password' id="password" placeholder='Password' class='input-box' name='password' onfocus='removeDefault(this.id)' onblur="restoreDefault(this.id)"/>
			<input type='submit' class="button margin-top" id='submit' value="Login" />
			<input type="hidden" name="next" value="/watsan/dashboard/" />
		</form>
		<a class="margin" href="/watsan/password_reset">Forgot password?</a>
	</div>
{% endblock %}

user_control/templates/pages/members.html
{% extends "settings/settings.html" %}

{% block form-tag %}
	<a id="add-new-member" class="link" href="#" onclick="$('#member-form').slideDown(); $('#add-new-member').slideUp();">Add a new member</a>
	<form id="member-form" method="post" action="/settings/members/" style="display: none">
		<a id="cancel-new-member" class="link" href="#" onclick="$('#member-form').slideUp(); $('#add-new-member').slideDown();">Cancel</a>
{% endblock %}

{% block form-contents %}
	<table>
		{{ member_form.as_table }}
	</table>
{% endblock %}

{% block extra-content %}
	{% if member_list %}
		<a id="delete-selected" style="display:none">Delete Selected</a>
		<table id="member-list">
			<tr>
				<th></th>
				<th>Name</th>
				<th>Email</th>
				<th>Username</th>
				<th>Created</th>
				<th>Last Login</th>
			</tr>
			{% for member in member_list %}
				<tr>
					<td><input type='checkbox' name="{{member.id}}" id="member-{{member.id}}" class="member-select"></input></td>
					<td>{{member.get_full_name}}</td>
					<td>{{member.email}}</td>
					<td>{{member.username}}</td>
					<td>{{member.date_joined}}</td>
					<td>{{member.last_login}}</td>
				</tr>
			{% endfor %}
		</table>
	{% endif %}
{% endblock %}

{% block script %}
	$(function() {
		{% if member_form.errors %}
			$("#member-form").slideDown();
		{% endif %}

		$(".member-select").click(function(e) {
			if ($(".member-select:checked").length > 0) {
				$("#delete-selected").fadeIn();
				$(".member-select:checked").parents('tr').hide().attr('class', 'white background-grey').fadeIn();
				$(".member-select:not(:checked)").parents('tr').attr('class', 'background-white grey').show();
			} else {
				$("#delete-selected").fadeOut();
				$(".member-select:checked").parents('tr').hide().attr('class', 'white background-grey').fadeIn();
				$(".member-select:not(:checked)").parents('tr').attr('class', 'background-white grey').show();
			}
		});

		$("#delete-selected").click(function() {
			var deadMembers = '';
			$(".member-select:checked").each(function(i, e) {
				deadMembers += e.id.replace(/member-/g, '') + ',';
			});
			$.post('/user/delete/' + deadMembers + '/', {'csrfmiddlewaretoken': '{{ csrf_token }}'})
				.complete(function() { window.location.href = window.location.href; });
		});

		$("#id_is_admin").click(function() {
			if ($("#id_is_admin:checked").length > 0) {
				if ($("#id_can_export_data:not(:checked)").length > 0)
					$("#id_can_export_data").click();
				$("#id_can_export_data").attr('disabled', 'disabled');
			} else if ($("#id_is_admin:not(:checked)").length > 0) {
				$("#id_can_export_data").removeAttr('disabled');
			}
		});
	});
{% endblock %}

user_control/templates/pages/signup.html
{% extends "base_map/base.html" %}

{% block header_content %}
{% endblock %}

{% block content %}
	<div id='small-box' class="text-center">
		<h1 class="page-title">Sign Up</h1>
		{% if userform %}
		<form action="{% url 'signup' %}" method="POST">
			{% csrf_token %}
			<table>
			 {% for field in userform %}
				<tr>
					<td>{{ field.label_tag }} {% if not field.field.required %} <label>(optional)</label> {% endif %}</td>
					<td>{{ field.errors }}{{ field }}</td>
				</tr>
			{% endfor %}
			</table>
			<div class='placeholder'>
				<div id='goto'><p>Already have an account? <a href="{% url 'default_login' %}">Sign In</a></p></div>
				<button id='done' class="btn success medium" type="submit" name="submit">Sign up</button> 
			</div>
		</form>
		{% else %}
		<p>Almost there! A confirmation email has been sent to your email address. Click the link in your email to access yur account.</p>
		{% endif %}
	</div>
{% endblock %}