user_control/urls.py
from django.conf.urls import *
    
urlpatterns = patterns('',
    url('', include('social.apps.django_app.urls', namespace='social')),
	(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'pages/login.html'}, 'default_login'),
    (r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/welcome/?next=/'}, 'default_logout'),

	(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'settings/password/change.html'}),
    (r'^password_change_done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'settings/password/change_done.html'}),
    (r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'template_name': 'settings/password/reset.html',
        'email_template_name': "email/reset_password.html",
        'post_reset_redirect': '/users/password_reset_done/'}, 'password_reset'),
    (r'^password_reset_done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'settings/password/reset_done.html'}, 'password_reset_done'),
    (r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': '/', 'template_name': 'settings/password/reset_confirm.html'}, 'password_reset_confirm'),
)

urlpatterns += patterns('user_control.views',
    (r'^delete/(?P<userIds>[\d,]{0,100})/$', 'delete_users'),
    url(r'^signup/$', 'signup', name='signup'),

    (r'^change_name/$', 'change_name'),
    (r'^change_email/$', 'change_email'),
    (r'^change_email_complete/(?P<hash_string>[0-9A-Za-z]+)/$', 'change_email_complete'),

    url(r'^confirm/(?P<confirmationCode>[\w\s\d]{0,20})/(?P<username>[\w\s\d]{0,50})/$', 'confirm', name="confirm"),
)

watsan/urls.py
from django.conf.urls import *
from django.contrib import admin, admindocs
from django.contrib.auth.views import logout, login, password_reset, password_reset_done, password_reset_complete, password_reset_confirm
from django.views.generic import RedirectView, TemplateView
from watsan.views import *

admin.autodiscover()
    
urlpatterns = [
    url(r'^landing/$', TemplateView.as_view(template_name="landing.html"), name='watsan_landing'),
    url(r'^login/$', login, {'template_name': 'registration/login.html'},  name='watsan_login'),
    url(r'^logout/$', logout, {'template_name': 'registration/login.html'}, name='watsan_logout' ),
    url(r'^$', RedirectView.as_view(url='/dashboard'), name='watsan_home'),

    url(r'^dashboard/$', dashboard, name='dashboard'),
    url(r'^map/(?P<projectId>[0-9]*)$', the_map),
    url(r'^project/(?P<projectId>[0-9]*)$', project),
    url(r'^ncwsc/(?P<projectId>[0-9]*)$', ncwsc),
    url(r'^alts/(?P<projectId>[0-9]*)$', alts),

    url(r'^register/$', RedirectView.as_view(url='/register/org'), name='watsan_register'),
    url(r'^register/org/$', register_org, name='watsan_register_org'),
    url(r'^register/user/$', register_user, name='watsan_register_user'),
    url(r'^register/final/$', register_final, name='watsan_register_final'),

    url(r'^password_reset/$', password_reset,
        {'template_name': 'password_reset/password_reset.html',
        'post_reset_redirect': '/watsan/password_reset_done/'}),
    url(r'^password_reset_done/$', password_reset_done, {'template_name': 'password_reset/password_reset_done.html'}),
    url(r'^password_reset_complete/$', password_reset_complete, {'template_name': 'password_reset/password_reset_complete.html'}),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, 
        {'post_reset_redirect' : '/watsan/password_reset_complete', 'template_name': 'password_reset/password_reset_confirm.html'}),

    url(r'^about/$', about, name='about'),
    url(r'^settings/$', settings, name='settings'),
    #(r'^settings/password_change/$', password_change, {'template_name': 'watsan/dashboard/password_change.html'}),
    #(r'^settings/password_change_done/$', password_change_done, {'template_name': 'watsan/dashboard/password_change_done.html'}),
    url(r'^settings/change_user_name/$', change_user_name),
    url(r'^settings/change_user_email/$', change_user_email),
    url(r'^settings/change_user_email_complete/(?P<hash_string>[0-9A-Za-z]+)/$', change_user_email_complete),
    
    url(r'^saveLandmark/$', save_landmark),
    url(r'^saveSearchString/$', save_search_string), 
    url(r'^map/site/save/$', save_site),
    url(r'^map/site/edit/$', edit_site),
    url(r'^map/site/delete/$', delete_site),
    url(r'^map/check_site/$', check_site_placement),
    url(r'^project/save/$', save_project),
    url(r'^admin/', admin.site.urls)
]

user_control/models.py
from django import forms
from django.contrib.gis.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.forms.widgets import RadioSelect, HiddenInput, PasswordInput

class UserProfile(models.Model):
    user = models.ForeignKey(User)
    next = models.CharField(default="/", max_length=100)

    number = models.CharField(max_length=20, blank=True)
    secondary_number = models.CharField(max_length=20, blank=True)
    gender = models.CharField(blank=True, choices=(('male', 'Male'), ('female', 'Female')), max_length=10)
    picture = models.ImageField(upload_to="UserAvatars", blank=True, null=True)
    has_mpesa = models.NullBooleanField()
    organization = models.CharField(max_length=255, blank=True)

    confirmation_code = models.CharField(max_length=20 ,blank=True, null=True)

    class Meta:
        app_label = 'user_control'
        db_table = 'user_control_userprofile'
    
    def __unicode__(self):
        return self.user.username+"'s profile"

class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    username = forms.CharField(max_length=30, required=True)

    old_password = forms.CharField(max_length=30, required=False, widget=PasswordInput())
    new_password = forms.CharField(max_length=30, required=False, widget=PasswordInput())
    new_password_again = forms.CharField(max_length=30, required=False, widget=PasswordInput())
    
    def clean(self):
        cleaned_data = super(UserEditForm, self).clean()
        old_password = cleaned_data.get("old_password")
        new_password = cleaned_data.get("new_password")
        new_password2 = cleaned_data.get("new_password_again")
        if old_password and new_password:
            if not self.instance.check_password(old_password):
                self._errors["old_password"] = self.error_class([u"Incorrect Password!"])
            elif not new_password2:
                self._errors["new_password_again"] = self.error_class([u"Must enter new password twice"])
            elif not new_password == new_password2:
                self._errors["new_password"] = self.error_class([u"Your new passwords didn't match!"])
        return cleaned_data
    
    class Meta:
        model = UserProfile
        fields = ('first_name','last_name','username', 'old_password','new_password','new_password_again')

class UserProfileForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    number = forms.CharField(max_length=20, required=False)
    secondary_number = forms.CharField(max_length=20, required=False)
    gender = forms.CharField(required=False, widget=forms.RadioSelect(choices=(('male', 'Male'), ('female', 'Female'))), max_length=10)
    picture = forms.ImageField(required=False)
    has_mpesa = forms.NullBooleanField(required=True, widget=RadioSelect(choices=((None, 'Unknown'), (True, 'Yes'), (False, 'No'))))
    organization = forms.CharField(required=False, max_length=255)
    
    class Meta:
        model = UserProfile
        fields = ('email','number','secondary_number','gender','picture','has_mpesa')
        exclude = ('user', 'next')
        
class AddMemberForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=False)
    number = forms.CharField(max_length=20, required=False)
    can_export_data = forms.BooleanField(required=False)
    is_admin = forms.BooleanField(help_text="This will enable this user to add and remove users, and make other major changes to your collective (including exporting data)", required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'number')

class NewUserForm(forms.ModelForm):
    username = forms.CharField(max_length=30, required=True)
    email = forms.EmailField()
    password1 = forms.CharField(label='Password',max_length=30, widget=PasswordInput())
    organization = forms.CharField(label='Organization', max_length=30, required=False)

    def clean_email(self):
        if self.is_valid():
            email = self.cleaned_data.get("email")
            if User.objects.filter(email=email).exists():
                self._errors["email"] = self.error_class([u"Email is already registered."])
                return False
            return email
        else:
            return False

    class Meta:
        model = User
        fields = ('username', 'email', 'password1','organization')

user_control/views.py
from django.shortcuts import render, redirect
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.contrib.auth.views import password_reset, password_reset_confirm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.contrib.sites.models import Site
from user_control.models import NewUserForm, UserProfile
from user_control import utils

def signup(request):
    if request.method == "POST":
        user_form = NewUserForm(request.POST)
        if user_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password1'])
            user.save()

            confirmation_code = utils.generate_confirmation_code()
            userprofile = UserProfile(user=user, confirmation_code=confirmation_code)
            userprofile.save()
            
            html_content = render_to_string('email/confirmation.html', { 'username': user.username, 'confirmation_code': confirmation_code, 'domain': Site.objects.get_current().domain })
            text_content = strip_tags(html_content) 
            message = EmailMultiAlternatives('Email Confirmation', text_content, 'connect@spatialcollective.com', [user.email])
            message.attach_alternative(html_content, "text/html")
            message.send()

            return render(request, 'pages/signup.html')
        return render(request, 'pages/signup.html', {'userform': user_form})
    else:
        user_form = NewUserForm()
        return render(request, 'pages/signup.html', {'userform': user_form})


def confirm(request, confirmationCode, username):
	user = User.objects.get(username=username)
	profile = UserProfile.objects.get(user=user)

	if profile.confirmation_code == confirmationCode:
		profile.confirmation_code = ''
		profile.save()
		user.save()

		html_content = render_to_string('email/welcome.html', { 'username': user.username })
		text_content = strip_tags(html_content) 
		message = EmailMultiAlternatives('Welcome to Spatial Collective!', text_content, 'connect@spatialcollective.com', [user.email])
		message.attach_alternative(html_content, "text/html")
		message.send()
		
		user.backend='django.contrib.auth.backends.ModelBackend'
		login(request, user)
	return redirect('home')



@login_required
def change_name(request):
	if request.method == 'POST':
		new_name = EditUserNameForm(request.POST).save(commit=False)
		request.user.first_name = new_name.first_name
		request.user.last_name = new_name.last_name
		request.user.save();
		return redirect('/settings')
	else:
		new_name_form = EditUserNameForm({'first_name': request.user.first_name, 'last_name': request.user.last_name })
		return render(request, 'settings/change_name.html', { 'new_name_form': new_name_form })

@login_required
def change_email(request):
	if request.method == 'POST':
		new_email_form = ChangeUserEmailForm(request.POST)
		if new_email_form.is_valid():
			new_email = new_email_form.save(commit=False)

			if User.objects.filter(email=new_email.email).exists():
				new_email_form._errors['email'] = new_email_form.error_class([u"That email is already registered."])
				return render(request, 'settings/email/change.html', {'new_email_form': new_email_form })
			else:
				new_email.user = request.user
				new_email.hash_string = uuid.uuid1().hex[:9]
				transfered = False
				new_email.save()

				message = render_to_string('watsan/email/change.html', { 'link': 'http://localhost:8000/watsan/settings/change_user_email_complete/'+new_email.hash_string })
				send_mail('Changing your email', message, 'kariuki@ishuah.com', [new_email.email])

			return render(request, 'settings/email/change_done.html')
		else:
			return render(request, 'settings/email/change.html', {'new_email_form': new_email_form })
	else:
		new_email_form = ChangeUserEmailForm()
		return render(request, 'settings/email/change.html', {'new_email_form': new_email_form })

def change_email_complete(request, hash_string):
	try:
		new_email = NewEmail.objects.get(hash_string=hash_string)
	except:
		return render(request, 'settings/email/change_error.html')
	user = new_email.user 
	user.email = new_email.email
	user.username = new_email.email
	user.save()

	new_email.transfered = True
	new_email.hash_string = ''
	new_email.save()

	if request.user.is_authenticated():
		logout(request)

	return render(request, 'settings/email/change_complete.html')

@permission_required('base_map.manage_map')
def delete_users(request, userIds=None):
	user_id_list = filter (lambda i:  i != ' ', userIds.split(','))
	count = 0
	for u  in user_id_list:
		if u and not User.objects.get(pk=u) == request.user:
			User.objects.get(pk=u).delete()
			count += 1
		elif u:
			messages.error(request, "Sorry, you can't delete yourself yet!")
	if count > 0:
		messages.success(request, "Deleted %i users" % (count))
	return redirect('/settings/members/')

user_control/templates/settings/password/change.html
{% extends "base_map/base.html" %}

{% block content %}
<h3 class="text-center">Password Change</h3>
<p class="text-center">
    Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly.
</p>
<form class="text-center" action="" method="post">
    {% csrf_token %}
    <table style="margin: 0 auto;">
        <tr>
            <td><label for="id_old_password" class="required">Old password</label></td>
            <td><input style="border:1px solid black; font-size:1.3em; padding:5px;" id="id_old_password" name="old_password" type="password">
             {% if form.old_password.errors %}
               {{ form.old_password.errors }}
            {% endif %}
            </td>

        </tr>
        <tr>
            <td><label for="id_new_password1" class="required">New password</label></td>
            <td><input style="border:1px solid black; font-size:1.3em; padding:5px;" id="id_new_password1" name="new_password1" type="password">
             {% if form.new_password2.errors %}
               {{ form.new_password2.errors }}
            {% endif %}
            </td>
        </tr>
        <tr>
            <td><label for="id_new_password2" class="required">Password (again)</label></td>
            <td><input style="border:1px solid black; font-size:1.3em; padding:5px;" id="id_new_password2" name="new_password2" type="password"></td>
        </tr>
    </table>
    
        
            <input type="submit" value="Change my password" class="btn">
        <p class="lead text-center"><a href="url 'watsan.views.settings' ">Back to settings page</a></p>
</form>
{% endblock %}

user_control/templates/settings/password/change_done.html
{% extends "watsan/dashboard/base.html" %}

{% block content %}
<div class="row">
    <div class="column_6 offset_3 padding margin-top">
		<h3 class="text center margin-bottom">Password change successful</h3>
		<p class="text center">Your password was changed.</p>
		<p class="text center bold"><a href="{% url 'watsan.views.settings' %}">Back to settings page</a></p>
	</div>
</div>
{% endblock %}

user_control/templates/settings/password/reset.html
{% extends "base_map/base.html" %}

{% block content %}
	<div id="small-box">
		<h1 class="page-title text-center">Password Reset</h1>
		<p>Enter your email address, you will receive a link that will direct you to a reset page.</p>
		<form class="text-center" action="" method="POST">
			{% csrf_token %}
			{% if form.email.errors %}
				{{ form.email.errors }}
			{% endif %}
			<label class='padding-right'>Email:</label>
			{{ form.email }}
			<div class='placeholder'>
				<div id='goto'>
					<a href="{% url 'default_login' %}">Log In</a>
					<a href="{% url 'signup' %}">Sign Up</a>
				</div>
				<input id='done' class="btn success medium" type="submit" name="submit" value='Submit' />
			</div>
		</form>	
	</div>
{% endblock %}

user_control/templates/settings/password/reset_complete.html
{% extends "base_map/base.html" %}

{% block content %}
	<div id='small-box'> 
		<h1 class="page-title text-center">Password Changed</h1>
		<p class="lead text-center">Success! Your password has been changed.</p>
		<div class='placeholder'>
			<a id='done' class="btn success medium" href="{% url 'default_login' %}">Log in</a>
		</div>
	</div>
{% endblock %}

user_control/templates/settings/password/reset_confirm.html
{% extends "base_map/base.html" %}

{% block content %}
    <div id="small-box">
        {% if validlink %}
            <h1 class="page-title text-center">Change password</h1>
            <p class='text-center'>Please enter your new password twice</p>
            <form class="text-center" action="" method="POST">
                {% csrf_token %}
                <table>
                    <tr><td colspan="2">{{ form.new_password1.errors }}</td></tr>
                    <tr>
                        <td><label for="id_new_password1" class="required">New password:</label></td>
                        <td>{{ form.new_password1 }}</td>
                    </tr>
                    <tr><td colspan="2">{{ form.new_password2.errors }}</td></tr>
                    <tr>
                        <td><label for="id_new_password2" class="required">Password (again):</label></td>
                        <td>{{ form.new_password2 }}</td>
                    </tr>
                </table>
                <div class='placeholder'>   
                    <input id='done' class="btn success medium" type="submit" name="submit" value='Submit' />
                </div>       
            </form>
        {% else %}
            <h1 class="page-title text-center">Password reset unsuccessful</h1>
            <p>The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
        {% endif %}
{% endblock %}

user_control/templates/settings/password/reset_done.html
{% extends "base_map/base.html" %}

{% block content %}
	<div id="small-box">
		<h1 class="page-title text-center">Password Reset Successful</h1>
		<p>We've e-mailed you instructions for resetting your password. You should be receiving it shortly.</p>
		<p><b>Please Note:</b> If you don't see the email in your inbox check your spam/junk folder</p>
		<div class='placeholder'>
			<div id='goto'>
				<a href="{% url 'default_login' %}">Log In</a>
				<a href="{% url 'signup' %}">Sign Up</a>
			</div>
		</div>
	</div>
{% endblock %}